### ISSUE TITLE
Adding support for Chromium in the default Unix  binaries

### ISSUE THREAD

**Issue by offray** [astares/Pharo-Chrome#10]
Hi and thanks for this project. I have been using it for the [MiniDocs](https://code.sustrato.red/Offray/MiniDocs) package, which extends documentation capabilities of [Lepiter](https://lepiter.io/feenk/introducing-lepiter--knowledge-management--e2p6apqsz5npq7m4xte0kkywn/) with light formats, including [Mardeep](https://casual-effects.com/markdeep/) preview and exportation.

A single line could be [added to UnixChromePlatform class >>defaultExecutableLocations](https://code.sustrato.red/Offray/MiniDocs/src/commit/f0c0a537a/src/MiniDocs/UnixChromePlatform.extension.st), so Pharo-Chrome would detect installations of Chromium in Unix, for those of us that prefer it over Chrome.

Thanks.

**Comment by astares** [comment]
@offray Sure - if you need it quick just send a PR

**Comment by offray** [comment]
@astares I'm not in any particular rush, so I will wait. Thought I will be happy of learning about Git based workflows, particularly on Pharo/GToolkit.

**Comment by astares** [comment]
On my system I used snap now to install. So we have to additionally add " '/snap/bin/chromium'" as a possible path

**Comment by astares** [comment]
@offray Fixed
